### ISSUE TITLE
Issue with plugin activation.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/push-notification#103]
When we try to activate the fresh PN plugin, there is an error while activating it.

Ref video: https://www.loom.com/share/848126dacf12455b9aa254cfc4e23c62?from_recorder=1&focus_title=1 

issue found in our local host

**Comment by MohammedAkramU7** [comment]
Another user facing same issue: https://magazine3.in/conversation/257278?folder_id=21

**Comment by Sanjeevsetu** [comment]
This ticket has been pushed in v1.33.1
