### ISSUE TITLE
Integration with BuddyBoss

### ISSUE THREAD

**Issue by ellbe69** [ahmedkaludi/push-notification#16]
Hi! I would love to have integration with BuddyBoss and PWA for Wordpress so that members would get notifications if someone sends them a message or mentions them or replies to a post.

**Comment by jkw224** [comment]
+1 PWA integration for BuddyBoss

**Comment by MohammedAkramU7** [comment]
Another user facing the issue ref ticket:-https://magazine3.in/conversation/61249?folder_id=21
