### ISSUE TITLE
Need to create a documentation for sending notification to specific user

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/push-notification#21]
The user would like to send a push notification to a specific WP user who registered on the site.

Message from the user:
"Ideally I can make that push notification request using the WP REST API.
We are building a company intranet in wordpress and want to send important notices to specific users at times."

Ref: https://secure.helpscout.net/conversation/1440743277/183172?folderId=3514643

**Comment by ankit644** [comment]
The user want to connect the plugin with the mobile app for the mobile notifications

Message from the user:-
"how can I connect the plugin with the mobile app for the mobile notifications?"

Refrance: https://secure.helpscout.net/conversation/1597702571/209459?folderId=4874234

**Comment by Sanjeevsetu** [comment]
It is related to documentation. I am moving it to trello
