### ISSUE TITLE
Critical error when changing order status via the WC Orders screen

### ISSUE THREAD

**Issue by krugazul** [ahmedkaludi/push-notification#23]
### Description

When we switch an order from processing to complete,  or to any status. It generates a critical error, and the site white screens.

This may be due to the use of PHP 8.0.8

```An error of type E_ERROR was caused in line 635 of the file /httpdocs/wp-content/plugins/push-notification/inc/admin/admin.php. Error message: Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, string given in /httpdocs/wp-content/plugins/push-notification/inc/admin/admin.php:635```

### Solution
I added the following code to [line 617 - admin.php](https://github.com/ahmedkaludi/push-notification/blob/master/inc/admin/admin.php#L617) and it fixed the problem.

```
if ( ! is_array( $token_ids ) ) {
	$token_ids = array( $token_ids );
}
```

### WordPress Environment ###
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: ❌ 5.7.2 - There is a newer version of WordPress available (5.8)
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.1
PHP Version: 8.0.8
cURL Version: 7.52.1
OpenSSL/1.0.2u

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

**Comment by Sanjeevsetu** [comment]
Related https://github.com/ahmedkaludi/push-notification/issues/75
