### ISSUE TITLE
Need to customize option for notification banner

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/push-notification#24]
Reference Ticket URL: https://secure.helpscout.net/conversation/1690745888/217145?folderId=4409869

Need to have some customized options for notification banners.
User request for a design like below screenshot(https://prnt.sc/1zvg4d8)

**Comment by Sanjeevsetu** [comment]
Related https://github.com/ahmedkaludi/push-notification/issues/76
