### ISSUE TITLE
Fatal Error : Uncaught Error: explode(): Argument #2 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/push-notification#38]
wp-content/plugins/push-notification/inc/admin/admin.php:1030
![fatal error](https://user-images.githubusercontent.com/11539242/203992607-d35e7561-1182-471b-8cf5-8270d073fcdc.png)

**Comment by akshaywali** [comment]
pushed in version 1.25
