### ISSUE TITLE
Redirect to a 404 page by clicking the "Subscribe for notification" button on the AMP page.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/push-notification#42]
Bug: Redirect to a 404 page by clicking the "**Subscribe for notification**" button on the AMP page.
Plugin Version: 1.25.1
Bug reported by: User
Ref ticket: https://magazine3.in/conversation/89263?folder_id=27
Ref video: https://monosnap.com/direct/CHcz2Vw0UE7FP0Et6KKXbjQanTkbKi

**Comment by akshaywali** [comment]
update pushed in 1.26 version
