### ISSUE TITLE
Need to create a feature where users can only set notifications and  prompts only on mobile

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/push-notification#49]
There is a need to create a new feature where the user can set the push notifications and prompts only on mobile, not on desktop.

Ref Ticket : https://magazine3.in/conversation/119827?folder_id=29

**Comment by mohammed-qutubuddin** [comment]
One more user request for the option where we can hide the notification subscribe popup on the desktop devices.
https://magazine3.in/conversation/55081?folder_id=19

**Comment by Sanjeevsetu** [comment]
Related https://github.com/ahmedkaludi/push-notification/issues/95
