### ISSUE TITLE
Need to add the compatibility "iOS update 16.4 has added the Push Notification support in Web Apps"

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/push-notification#56]
Need to add the compatibility "iOS update 16.4 has added the Push Notification support in Web Apps"

Ref ticket: https://magazine3.in/conversation/145098?folder_id=27

Ref Article: https://www.inverse.com/tech/how-to-push-notifications-web-apps-ios-16

**Comment by akshaywali** [comment]
pushed in 1.28
