### ISSUE TITLE
We need to create an option to customise the push notification banner.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/push-notification#76]
We need to create an option so that we can customise and add CSS to push notifications Banner

Ref screenshoot : https://prnt.sc/TfTkD7BLJ3Tm To add the CSS on "OK" and 'No Thanks,' button 

Ref Ticket:https://magazine3.in/conversation/224612?folder_id=29

**Comment by Sanjeevsetu** [comment]
Reference Ticket URL: https://secure.helpscout.net/conversation/1690745888/217145?folderId=4409869

Need to have some customized options for notification banners.
User request for a design like below screenshot(https://prnt.sc/1zvg4d8)

**Comment by akshaywali** [comment]
pushed in version 1.34
