### ISSUE TITLE
code improvement

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/push-notification#82]
- [x] nonce check missing fun 'pn_send_feedback', 
- [x] No need to escape empty string \inc\admin\admin.php Line : 209, 245, 
- [x] html tags should not be include inside translation and use esc_html__(  instead of __( \inc\admin\admin.php Line : 226, 238 
- [x] escaping is missing \inc\admin\admin.php Line : 503, 506, 515, 524, 528, 537, 541, 553, 552, 555, 575, 607, 612, 1035, 1038, 1046, 1055, 1059, 1068, 1072, 1083, 1084, 1086, 1540, 1541, 1542, 1553, 1563, 1570, 1571, 
- [x] before array_merge validation check must be there \inc\admin\admin.php Line : 641, check entire plugin
- [x] use wp_json_encode everywhere in plugin
- [x] validate data before every foreach loop in whole plugin to avoid future warnings and fatal error
- [x] sanitize as earliest of $_POST or $_GET . \inc\admin\admin.php Line : 848, 850, 1312, 1313, 1314
- [x] escaping is not correct \inc\admin\admin.php Line : 1210, 1317
- [x] escaping is missing inc\frontend\amp-pn-subscribe.php Line : 37, 39 
- [x] escaping is missing inc\frontend\amp-pn-frontend.php Line : 276, 279, 282, 
- [x] wrong fun prefix search 'pwaforwp_notification_confirm_banner'
- [x] why we are getting whole categories inside fun 'pwaforwp_notification_confirm_banner', it will slow down the process. just discuss with @Sanjeevsetu 
- [x] defined debug_script to serve minified js and css in production

**Comment by akshaywali** [comment]
pushed in version 1.32
